#!/bin/bash
TOP=$(dirname $0)
TOP=$(cd $TOP && pwd)
_3P=${TOP}/third_party
PYENV=${TOP}/.pyenv
VIRTUAL_ENV_VER=1.9.1
VIRTUAL_ENV_TAR=${_3P}/virtualenv-${VIRTUAL_ENV_VER}.tar.gz
VIRTUAL_ENV_DIR=${_3P}/virtualenv-${VIRTUAL_ENV_VER}

tar -C ${_3P} -xzf ${VIRTUAL_ENV_TAR}
[ -z "$PYTHON" ] && PYTHON=python
$PYTHON ${VIRTUAL_ENV_DIR}/virtualenv.py ${PYENV}
rm -rf ${VIRTUAL_ENV_DIR}

source ${PYENV}/bin/activate
pip install -r ${_3P}/requirements.txt --find-links file://${_3P} --no-index
#pip install -r ${_3P}/requirements.txt --download-cache ${_3P}
